packages:
  - "."

allowBuilds:
  "@prisma/engines": false
  "@tailwindcss/oxide": true
  esbuild: true
  prisma: false
  sharp: true
  workerd: true

minimumReleaseAgeExclude:
  - miniflare@5.20260903.0-alpha
  - wrangler@4.129.0
  - astro@7.3.1
